### ISSUE TITLE
Code-server setup guide is incomplete

### ISSUE THREAD

**Issue by kralicky** [pomerium/documentation#1692]
Page: https://www.pomerium.com/docs/guides/code-server

## What's incorrect or missing

I had to make the following changes after completing the setup guide:

1. edit the code-server config file to add trusted-origins and proxy-domain:
```yaml
bind-addr: 0.0.0.0:8080 # this defaulted to 127.0.0.1
auth: none
cert: false
trusted-origins:
  - <route hostname>
proxy-domain: 
  - <route hostname>/proxy/{{port}}
```
2. turned off 'preserve host header' in pomerium route config

Before making these changes, the code-server websockets would not connect, failing with a 403 error. Additionally, subdomain port forwarding is the default, but the zero-provisioned certs don't support this. 

I think the trusted-origins setting is required to allow wss connections after we do tls termination.

The proxy-domain setting is not clearly documented, but it seems to both tell code-server the public URL it will be accessed from, as well as enable subpath port forwarding (based on the presence of `{{port}}` in the string). https://github.com/coder/code-server/blob/fc97e248c354be27a054c182669a6984dd73cd41/src/node/cli.ts#L604-L617
