### ISSUE TITLE
k8s reference: format enums

### ISSUE THREAD

**Issue by wasaga** [pomerium/documentation#71]
## What's incorrect or missing

Display allowed enums if they are provided by the spec: 

```
                  provider:
                    description: Provider one of accepted providers https://www.pomerium.com/reference/#identity-provider-name
                    enum:
                    - auth0
                    - azure
                    - google
                    - okta
                    - onelogin
                    - oidc
                    - ping
                    - github
                    type: string
```

## What's the resolution?

use `enum` field from the spec.
