### ISSUE TITLE
One of the ingress controller example policies looks off

### ISSUE THREAD

**Issue by kenjenkins** [pomerium/documentation#963]
Page: https://www.pomerium.com/docs/deploy/k8s/ingress

## What's incorrect or missing

I think this example policy is incorrect:

> ```yaml
> ingress.pomerium.io/policy: |
>   allow:
>   and:
>     - user:
>         is: user1@example.com
>     - user:
>         is: user2@example.com
> ```
>
> Users with matching emails would be allowed.

## What's the resolution?

The indentation should be fixed to nest the operator under the `allow` key, and the `and` should be an `or` if the intent is to allow either of the two email addresses:

```yaml
ingress.pomerium.io/policy: |
  allow:
    or:
      - user:
          is: user1@example.com
      - user:
          is: user2@example.com
```
